services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    # ports:
    #   - "5672:5672"    # AMQP
    #   - "15672:15672"  # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  worker:
    image: ghcr.io/romanghost/vdownloader_worker:${WORKER_TAG:-latest}
    command: ["./downloader", "-worker"]
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
      - OUT_DIR=/downloads
      - FILE_SERVER_ADDR=:8080
    ports:
      - "8080:8080"
    volumes:
      - downloads:/downloads
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  telegram:
    image: ghcr.io/romanghost/vdownloader_telegram:${TELEGRAM_TAG:-latest}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WORKER_URL=http://worker:8080
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    restart: unless-stopped

  web:
    image: ghcr.io/romanghost/vdownloader_web:${WEB_TAG:-latest}
    environment:
      - WORKER_URL=http://worker:8080
      - HTTP_ADDR=:8082
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
    restart: unless-stopped

volumes:
  downloads:
  rabbitmq_data:
